### ISSUE TITLE
Global tags in Open Data VM

### ISSUE THREAD

**Issue by katilp** [cms-opendata-analyses/AOD2NanoAODOutreachTool#1]
NB that without setting the GT as in
http://opendata.cern.ch/docs/cms-guide-for-condition-database
the producer does not run in the Open Data VM, but gives

CMS Shell > cmsRun configs/data_cfg.py
```
----- Begin Fatal Exception 26-Jan-2020 14:43:11 CET-----------------------
An exception of category 'Incomplete configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=PoolDBESSource label='GlobalTag'
Exception Message:
Valid site-local-config not found at /cvmfs/cms.cern.ch/SITECONF/local/JobConfig/site-local-config.xml
----- End Fatal Exception -------------------------------------------------
```

This is expected and due to the fact that in the Open Data VM one needs to access the condition data from /cvmfs/cms-opendata-conddb.cern.ch/ 

Note also that a different GT has been made available for 2012 data analysis, not FT_R_53_V18::All but FT53_V21A_AN6::All.

I would suggest that either the instructions in README point to http://opendata.cern.ch/docs/cms-guide-for-condition-database for the necessary changes  in case of running on the open data VM, or (probably better) that the these steps for collision data

```
ln -sf /cvmfs/cms-opendata-conddb.cern.ch/FT53_V21A_AN6_FULL FT53_V21A_AN6
ln -sf /cvmfs/cms-opendata-conddb.cern.ch/FT53_V21A_AN6_FULL.db FT53_V21A_AN6_FULL.db
ln -sf /cvmfs/cms-opendata-conddb.cern.ch/FT53_V21A_AN6_FULL FT53_V21A_AN6_FULL
```
and these for MC

```
ln -sf /cvmfs/cms-opendata-conddb.cern.ch/START53_V27 START53_V27
ln -sf /cvmfs/cms-opendata-conddb.cern.ch/START53_V27.db START53_V27.db
```

are explicitly written out in README,  and the configs are modified so that they have in configs/data_cfg.py

```
#globaltag for 2012 collision data
process.GlobalTag.connect = cms.string('sqlite_file:/cvmfs/cms-opendata-conddb.cern.ch/FT53_V21A_AN6_FULL.db')
process.GlobalTag.globaltag = 'FT53_V21A_AN6::All'
```
and in configs/simulation_cfg.py:

```
#globaltag for 2012 MC
process.GlobalTag.connect = cms.string('sqlite_file:/cvmfs/cms-opendata-conddb.cern.ch/START53_V27.db')
process.GlobalTag.globaltag = 'START53_V27::All'
```

I've now tested this and it works on the Open Data VM.  It takes the usual long time to get started because of reading the condition data to the VM cache. For data, the download started with:

```
Filesystem               1K-blocks    Used Available Use% Mounted on
...
cvmfs2                    20480000 1081219  19398781   6% /cvmfs/cvmfs-config.cern.ch
```

and ended with:

```
cvmfs2                    20480000 10931487   9548514  54% /cvmfs/cvmfs-config.cern.ch
```

Just for the record,  at the first try, with data_cfg.py (with the modifications above) I got the error below, but it may have been due to some time out, or due to the old feature that /cvmfs becomes "visible" only after first try to access it. The second try without further modifications runs smoothly.

```
CMS Shell > cmsRun configs/data_cfg.py 
CORAL/RelationalPlugins/sqlite Error SQLiteStatement::fetchNext 1 SQL logic error or missing database
CORAL/RelationalPlugins/sqlite Error SQLiteStatement::finalize 10 disk I/O error
CORAL/RelationalPlugins/sqlite Error SQLiteStatement::finalize 1 cannot commit - no transaction is active
CORAL/RelationalPlugins/sqlite Error SQLiteStatement::execute 1 cannot commit - no transaction is active
----- Begin Fatal Exception 26-Jan-2020 15:04:39 CET-----------------------
An exception of category 'StdException' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=PoolDBESSource label='GlobalTag'
Exception Message:
A std::exception was thrown.
cannot commit - no transaction is active ( CORAL : "SQLiteStatement::execute" from "CORAL/RelationalPlugins/sqlite" )
----- End Fatal Exception -------------------------------------------------
```

**Comment by katilp** [comment]
@stwunsch for the sake of completeness, I do not think this example, as it is now, needs the GT at all. If I run in a container without (to my knowledge) access to any cms frontier server, it still runs (as is now, i.e. with a GT - if needed by the job - to be read from a standard CMS location).
In addition, if I comment out:

`process.load('Configuration.StandardSequences.FrontierConditions_GlobalTag_cff')`

and

`process.GlobalTag.globaltag = "FT_R_53_V18::All"
`
it runs without problems.

**Comment by stwunsch** [comment]
Are the events still the same if we disable `process.load('Configuration.StandardSequences.FrontierConditions_GlobalTag_cff')`? That's not clear to me.

And if I update the code, how should we proceed with the copy on the portal?

**Comment by stwunsch** [comment]
I'm as well in favor of removing the global tag if possible, just for simplicity.

**Comment by stwunsch** [comment]
Ok, I've removed the global tag and checked with a data and signal sample that the result is the same. I'll open an issue on the portal to update the files.
